output_path: ???

path_latent: ???
path_samples: ???
path_gt: ???

levels:
  - 500
  - 1000

quantiles:
  - 0.05
  - 0.50
  - 0.95

show_samples: true
show_latent: false

tick_fontsize: 9
label_fontsize: 9
