reconstruction_path: ???
output_file: rmse_snapshots.pdf

# RMSE config
surface_variables:
  - 2m_temperature
  - 10m_u_component_of_wind
  - 10m_v_component_of_wind
  - mean_sea_level_pressure
  - sea_surface_temperature

atmospheric_variables:
  - temperature
  - u_component_of_wind
  - v_component_of_wind
  - geopotential
  - specific_humidity

ticks:
  levels:
    - 1000
    - 800
    - 600
    - 400
    - 200
    - 50
  error:
    - 0
    - 0.045
    - 0.09
    - 0.135
    - 0.18
  error_min: 0.0
  error_max: 0.18

styles:
  mean_sea_level_pressure:
    color: cyan
    marker: "+"
  sea_surface_temperature:
    color: orange
    marker: "x"
  temperature:
    color: red
    marker: "*"
  geopotential:
    color: magenta
    linestyle: ":"
  u_component_of_wind:
    color: blue
    linestyle: "-."
    marker: "o"
  v_component_of_wind:
    color: green
    linestyle: "-."
    marker: "s"
  specific_humidity:
    color: y
    linestyle: "-."

font_sizes:
  axis_label: 11
  legend: 10
  ticks: 11

# Snapshot config
snapshot_variables:  # List of up to 6 variables
  - name: 2m_temperature
    type: surface
  - name: 10m_u_component_of_wind
    type: surface
  - name: specific_humidity
    type: atmospheric
    level: 300  # hPa
  - name: geopotential
    type: atmospheric
    level: 300  # hPa
  - name: 10m_v_component_of_wind
    type: surface
  - name: total_precipitation
    type: surface

quantile_cmap: 0.01
center_europe: true
